# Information for specific cases
# key is the index as shown in the list of references (i.e. starting from 1)
edge_cases = {
    39  : { 'authors'     : [(None,'EDL')],
            'title'       : None,
            'journal'     : None,
            'institution' : 'Califonia Institute of Technology',
            'notes'       : 'unpublished',
            'year'        : None },
    94  : { 'authors'     : [('E.', 'Nzeyimana'), ('Tiggelen', 'Van')],
            'title'       : 'Influence of tetrafluoromethane on hydrogen-oxygen-argon detonations.',
            'journal'     : 'Prog. Astronaut. Aeronaut.',
            'vol'         : 133,
            'issue'       : None,
            'pages'       : '77-88',
            'institution' : None,
            'year'        : 1991 },
    111 : { 'authors'     : [('R.A.', 'Strehlow'), ('R.E.', 'Maurer'), ('S.', 'Rajan')],
            'title'       : 'Transverse waves in detonations: I. spacings in the hydrogen-system.',
            'journal'     : 'AIAA J.',
            'vol'         : 7,
            'issue'       : 2,
            'pages'       : '323-328',
            'institution' : None,
            'year'        : 1969 },
    118 : { 'authors'     : [('Molen', 'Vander'), ('J.A.', 'Nicholls')],
            'title'       : 'Blast wave initiation energy for the detonation of methane-ethane-air mixtures.',
            'journal'     : 'Combust. Sci. Technol.',
            'vol'         : 21,
            'issue'       : 1,
            'pages'       : '75-78',
            'institution' : None,
            'year'        : 1979 }
}
