# Information for specific cases
# key is the index as shown in the list of references (i.e. starting from 1)
edge_cases = {
    39  : { 'authors'     : [(None,'EDL')],
            'title'       : None,
            'journal'     : None,
            'institution' : 'Califonia Institute of Technology',
            'notes'       : 'unpublished',
            'year'        : None },
    50  : { 'authors'     : [('T.','Hikita'), (None,'et al.')],
            'title'       : 'A report on the experimental results of explosions and fires of liquid ethylene facilities',
            'journal'     : 'Technical Report',
            'vol'         : None,
            'issue'       : None,
            'pages'       : None,
            'institution' : 'Safety Information Centre, Institution for Safety of High Pressure Gas Engineering, Tokyo, Japan',
            'year'        : 1975 },
    51  : { 'authors'     : [('Z.W.', 'Huang'), ('Tiggelen', 'Van')],
            'title'       : 'Experimental study of the fine structure in spin detonations',
            'journal'     : 'Prog. Astronaut. Aeronaut.',
            'vol'         : 153,
            'issue'       : None,
            'pages'       : '132-143',
            'institution' : None,
            'year'        : 1993 },
    71  : { 'authors'     : [('M.H.', 'Lefebvre'), ('E.', 'Nzeyimana'), ('Tiggelen', 'Van')],
            'title'       : 'Influence of fluorocarbons on H_2-O_2-Ar detonation: Experiments and modeling',
            'journal'     : 'Prog. Astronaut. Aeronaut.',
            'vol'         : 153,
            'issue'       : None,
            'pages'       : '144-161',
            'institution' : None,
            'year'        : 1993 },
    72  : { 'authors'     : [('J.C.', 'Libouton'), ('M.', 'Dormal'), ('Tiggelen', 'Van')],
            'title'       : 'The role of chemical kinetics on structure of detonation waves',
            'journal'     : 'Prog. Astronaut. Aeronaut.',
            'vol'         : None,
            'issue'       : None,
            'pages'       : '79-86',
            'institution' : None,
            'year'        : 1975 },
    94  : { 'authors'     : [('E.', 'Nzeyimana'), ('Tiggelen', 'Van')],
            'title'       : 'Influence of tetrafluoromethane on hydrogen-oxygen-argon detonations',
            'journal'     : 'Prog. Astronaut. Aeronaut.',
            'vol'         : 133,
            'issue'       : None,
            'pages'       : '77-88',
            'institution' : None,
            'year'        : 1991 },
    108  : { 'authors'     : [('R.A.', 'Strehlow')],
            'title'       : 'Transverse waves in detonations: II. structure and spacing in H_2-O_2, C_2H_2-O_2, C_2H_4-O_2 and CH_4-O_2 systems',
            'journal'     : 'AIAA J.',
            'vol'         : 7,
            'issue'       : 3,
            'pages'       : '492-496',
            'institution' : None,
            'year'        : 1969 },
    111 : { 'authors'     : [('R.A.', 'Strehlow'), ('R.E.', 'Maurer'), ('S.', 'Rajan')],
            'title'       : 'Transverse waves in detonations: I. spacings in the hydrogen-system',
            'journal'     : 'AIAA J.',
            'vol'         : 7,
            'issue'       : 2,
            'pages'       : '323-328',
            'institution' : None,
            'year'        : 1969 },
    118 : { 'authors'     : [('Molen', 'Vander'), ('J.A.', 'Nicholls')],
            'title'       : 'Blast wave initiation energy for the detonation of methane-ethane-air mixtures',
            'journal'     : 'Combust. Sci. Technol.',
            'vol'         : 21,
            'issue'       : 1,
            'pages'       : '75-78',
            'institution' : None,
            'year'        : 1979 },
    119 : { 'authors'     : [('M.', 'Vandermeiren'), ('Tiggelen', 'Van')],
            'title'       : 'Cellular structure in detonation of acetylene-oxygen mixtures',
            'journal'     : 'Prog. Astronaut. Aeronaut.',
            'vol'         : 94,
            'issue'       : None,
            'pages'       : '104-117',
            'institution' : None,
            'year'        : 1984 },
    120 : { 'authors'     : [('M.', 'Vandermeiren'), ('Tiggelen', 'Van')],
            'title'       : 'Role of an inhibitor on the onset of gas detonations in acetylene mixtures',
            'journal'     : 'Prog. Astronaut. Aeronaut.',
            'vol'         : 114,
            'issue'       : None,
            'pages'       : '186-200',
            'institution' : None,
            'year'        : 1988 },
    124 : { 'authors'     : [('A.A.', 'Vasil\'ev'), ('Yu.A.', 'Nikolaev'), ('Yu.V.', 'Ul\'yanitskii')],
            'title'       : 'Role of an inhibitor on the onset of gas detonations in acetylene mixtures',
            'journal'     : 'Combust. Explos. Shock Waves (USSR)',
            'vol'         : 13,
            'issue'       : 3,
            'pages'       : '338-341',
            'institution' : None,
            'year'        : 1977 },
}
