recognized_keys = {
'fuel' : 'fuel',
'oxidizer' : 'oxidizer',
'diluent' : 'diluent',
'pressure' : 'pressure',
'temperature' : 'temperature',
'er' : 'er',
'author' : 'author',
'year' : 'year',
'journal' : 'journal',
'f' : 'fuel',
'o' : 'oxidizer',
'ox' : 'oxidizer',
'd' : 'diluent',
'dil' : 'diluent',
'p' : 'pressure',
't' : 'temperature',
'temp' : 'temperature',
'a' : 'author',
'auth' : 'author',
'y' : 'year',
'j' : 'journal',
'name' : 'name',
'id' : 'name',
'category' : 'category',
'cat' : 'category',
'c' : 'category',
'subcat' : 'subcategory',
'sc' : 'subcategory',
'subcategory' : 'subcategory',
'x' : 'x',
'y' : 'y'
}

json_keys = {
    'er' : None,
    'pressure' : None,
    'temperature' : None,
}

values = {
'methane' : 'ch4',
'ethane' : 'c2h6',
'hydrogen' : 'h2',
'oxygen' : 'o2',
'nitrogen' : 'n2',
'ethylene' : 'c2h4',
'acetylene' : 'c2h2',
# Some possible typos
'h1' : 'h2',
'h3' : 'h2',
'ch3' : 'ch4',
'ch5' : 'ch4',
'c1h6' : 'c2h6',
'c1h4' : 'c2h4',
'c1h2' : 'c2h2',
'shep' : 'shepherd',
'shephard' : 'shepherd',
'sheperd' : 'shepherd',
'kyianda' : 'kiyanda'
}
